ALTER TABLE LP_LABEL_TEMPLATE_ELEMENT
    ADD visible_when_field VARCHAR(100);

ALTER TABLE LP_LABEL_TEMPLATE_ELEMENT
    ADD visible_when_operator VARCHAR(40);

ALTER TABLE LP_LABEL_TEMPLATE_ELEMENT
    ADD visible_when_value VARCHAR(255);
